[project]
name = "GBReader"
version = "2023.1"
description = "Simplified Chinese (gb2312) reader for NVDA"
requires-python = ">=3.13"
dependencies = []

[tool.flake8]
ignore = ["E501", "F824"]
builtins = ["_"]
